/Users/richa.sethi/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
INFO:config:Configuration loaded successfully
INFO:config:Using Databricks host: e2-demo-field-eng.cloud.databricks.com
INFO:config:Using warehouse HTTP path: /sql/1.0/warehouses/862f1d757f0424f7
INFO:databricks.sdk:loading DEFAULT profile from ~/.databrickscfg: host, warehouse_id
INFO:databricks.sdk:Using Databricks CLI authentication
INFO:databricks.sdk:loading DEFAULT profile from ~/.databrickscfg: host, warehouse_id
INFO:databricks.sdk:Using Databricks CLI authentication
INFO:__main__:Starting Product Features Dashboard...
Dash is running on http://127.0.0.1:8050/

INFO:dash.dash:Dash is running on http://127.0.0.1:8050/

 * Serving Flask app 'app'
 * Debug mode: on
/Users/richa.sethi/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
INFO:config:Configuration loaded successfully
INFO:config:Using Databricks host: e2-demo-field-eng.cloud.databricks.com
INFO:config:Using warehouse HTTP path: /sql/1.0/warehouses/862f1d757f0424f7
INFO:databricks.sdk:loading DEFAULT profile from ~/.databrickscfg: host, warehouse_id
INFO:databricks.sdk:Using Databricks CLI authentication
INFO:databricks.sdk:loading DEFAULT profile from ~/.databrickscfg: host, warehouse_id
INFO:databricks.sdk:Using Databricks CLI authentication
INFO:__main__:Starting Product Features Dashboard...
